import gsap from "gsap";
import { ScrollTrigger, SplitText } from "gsap/all";
import Navbar from "./Components/Navbar";

gsap.registerPlugin(ScrollTrigger, SplitText);

const App = () => {
  return (
    <main>
        <Navbar />
        <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit reprehenderit soluta explicabo, quam ea, alias maxime praesentium pariatur quia, distinctio sed quasi corporis eum perferendis. Fugiat dolorem ratione ipsa commodi. Dicta harum velit quam sint tempore eveniet minima? Asperiores, harum. Tempore deserunt quaerat cumque? Fugiat, est autem unde libero incidunt magni expedita vero nostrum accusantium, soluta, impedit illo assumenda cupiditate quo totam. Eaque amet ipsa laboriosam itaque, incidunt totam inventore nemo reprehenderit porro quos tenetur animi enim! Dolorem sed quasi quo obcaecati maiores, eos minus dolorum ullam quidem, voluptatibus, odio praesentium a! Inventore ad nesciunt error molestias consequuntur qui nemo vitae, distinctio necessitatibus cumque debitis laudantium dignissimos ex accusantium explicabo neque quasi? Dolore, libero porro earum a ipsa nobis quod consequuntur aut maxime repellat expedita cum quaerat labore recusandae voluptas iusto esse ad, sit commodi debitis, excepturi velit nulla accusantium. A eveniet excepturi nihil eaque eligendi repudiandae, eos suscipit rerum iure veritatis modi incidunt, quos hic mollitia impedit. Repellat placeat ut velit, id molestiae eos tenetur aspernatur. Vero, enim repellat. Illo unde, perferendis ducimus dolor mollitia minima perspiciatis, voluptatum explicabo quam, sit fugiat. Reiciendis veritatis cupiditate laudantium cum voluptate eveniet nihil cumque provident, odit possimus, optio culpa facere eos perferendis!
        </p>
        <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit reprehenderit soluta explicabo, quam ea, alias maxime praesentium pariatur quia, distinctio sed quasi corporis eum perferendis. Fugiat dolorem ratione ipsa commodi. Dicta harum velit quam sint tempore eveniet minima? Asperiores, harum. Tempore deserunt quaerat cumque? Fugiat, est autem unde libero incidunt magni expedita vero nostrum accusantium, soluta, impedit illo assumenda cupiditate quo totam. Eaque amet ipsa laboriosam itaque, incidunt totam inventore nemo reprehenderit porro quos tenetur animi enim! Dolorem sed quasi quo obcaecati maiores, eos minus dolorum ullam quidem, voluptatibus, odio praesentium a! Inventore ad nesciunt error molestias consequuntur qui nemo vitae, distinctio necessitatibus cumque debitis laudantium dignissimos ex accusantium explicabo neque quasi? Dolore, libero porro earum a ipsa nobis quod consequuntur aut maxime repellat expedita cum quaerat labore recusandae voluptas iusto esse ad, sit commodi debitis, excepturi velit nulla accusantium. A eveniet excepturi nihil eaque eligendi repudiandae, eos suscipit rerum iure veritatis modi incidunt, quos hic mollitia impedit. Repellat placeat ut velit, id molestiae eos tenetur aspernatur. Vero, enim repellat. Illo unde, perferendis ducimus dolor mollitia minima perspiciatis, voluptatum explicabo quam, sit fugiat. Reiciendis veritatis cupiditate laudantium cum voluptate eveniet nihil cumque provident, odit possimus, optio culpa facere eos perferendis!
        </p>
        <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit reprehenderit soluta explicabo, quam ea, alias maxime praesentium pariatur quia, distinctio sed quasi corporis eum perferendis. Fugiat dolorem ratione ipsa commodi. Dicta harum velit quam sint tempore eveniet minima? Asperiores, harum. Tempore deserunt quaerat cumque? Fugiat, est autem unde libero incidunt magni expedita vero nostrum accusantium, soluta, impedit illo assumenda cupiditate quo totam. Eaque amet ipsa laboriosam itaque, incidunt totam inventore nemo reprehenderit porro quos tenetur animi enim! Dolorem sed quasi quo obcaecati maiores, eos minus dolorum ullam quidem, voluptatibus, odio praesentium a! Inventore ad nesciunt error molestias consequuntur qui nemo vitae, distinctio necessitatibus cumque debitis laudantium dignissimos ex accusantium explicabo neque quasi? Dolore, libero porro earum a ipsa nobis quod consequuntur aut maxime repellat expedita cum quaerat labore recusandae voluptas iusto esse ad, sit commodi debitis, excepturi velit nulla accusantium. A eveniet excepturi nihil eaque eligendi repudiandae, eos suscipit rerum iure veritatis modi incidunt, quos hic mollitia impedit. Repellat placeat ut velit, id molestiae eos tenetur aspernatur. Vero, enim repellat. Illo unde, perferendis ducimus dolor mollitia minima perspiciatis, voluptatum explicabo quam, sit fugiat. Reiciendis veritatis cupiditate laudantium cum voluptate eveniet nihil cumque provident, odit possimus, optio culpa facere eos perferendis!
        </p>
        <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit reprehenderit soluta explicabo, quam ea, alias maxime praesentium pariatur quia, distinctio sed quasi corporis eum perferendis. Fugiat dolorem ratione ipsa commodi. Dicta harum velit quam sint tempore eveniet minima? Asperiores, harum. Tempore deserunt quaerat cumque? Fugiat, est autem unde libero incidunt magni expedita vero nostrum accusantium, soluta, impedit illo assumenda cupiditate quo totam. Eaque amet ipsa laboriosam itaque, incidunt totam inventore nemo reprehenderit porro quos tenetur animi enim! Dolorem sed quasi quo obcaecati maiores, eos minus dolorum ullam quidem, voluptatibus, odio praesentium a! Inventore ad nesciunt error molestias consequuntur qui nemo vitae, distinctio necessitatibus cumque debitis laudantium dignissimos ex accusantium explicabo neque quasi? Dolore, libero porro earum a ipsa nobis quod consequuntur aut maxime repellat expedita cum quaerat labore recusandae voluptas iusto esse ad, sit commodi debitis, excepturi velit nulla accusantium. A eveniet excepturi nihil eaque eligendi repudiandae, eos suscipit rerum iure veritatis modi incidunt, quos hic mollitia impedit. Repellat placeat ut velit, id molestiae eos tenetur aspernatur. Vero, enim repellat. Illo unde, perferendis ducimus dolor mollitia minima perspiciatis, voluptatum explicabo quam, sit fugiat. Reiciendis veritatis cupiditate laudantium cum voluptate eveniet nihil cumque provident, odit possimus, optio culpa facere eos perferendis!
        </p>
        <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit reprehenderit soluta explicabo, quam ea, alias maxime praesentium pariatur quia, distinctio sed quasi corporis eum perferendis. Fugiat dolorem ratione ipsa commodi. Dicta harum velit quam sint tempore eveniet minima? Asperiores, harum. Tempore deserunt quaerat cumque? Fugiat, est autem unde libero incidunt magni expedita vero nostrum accusantium, soluta, impedit illo assumenda cupiditate quo totam. Eaque amet ipsa laboriosam itaque, incidunt totam inventore nemo reprehenderit porro quos tenetur animi enim! Dolorem sed quasi quo obcaecati maiores, eos minus dolorum ullam quidem, voluptatibus, odio praesentium a! Inventore ad nesciunt error molestias consequuntur qui nemo vitae, distinctio necessitatibus cumque debitis laudantium dignissimos ex accusantium explicabo neque quasi? Dolore, libero porro earum a ipsa nobis quod consequuntur aut maxime repellat expedita cum quaerat labore recusandae voluptas iusto esse ad, sit commodi debitis, excepturi velit nulla accusantium. A eveniet excepturi nihil eaque eligendi repudiandae, eos suscipit rerum iure veritatis modi incidunt, quos hic mollitia impedit. Repellat placeat ut velit, id molestiae eos tenetur aspernatur. Vero, enim repellat. Illo unde, perferendis ducimus dolor mollitia minima perspiciatis, voluptatum explicabo quam, sit fugiat. Reiciendis veritatis cupiditate laudantium cum voluptate eveniet nihil cumque provident, odit possimus, optio culpa facere eos perferendis!
        </p>
        <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit reprehenderit soluta explicabo, quam ea, alias maxime praesentium pariatur quia, distinctio sed quasi corporis eum perferendis. Fugiat dolorem ratione ipsa commodi. Dicta harum velit quam sint tempore eveniet minima? Asperiores, harum. Tempore deserunt quaerat cumque? Fugiat, est autem unde libero incidunt magni expedita vero nostrum accusantium, soluta, impedit illo assumenda cupiditate quo totam. Eaque amet ipsa laboriosam itaque, incidunt totam inventore nemo reprehenderit porro quos tenetur animi enim! Dolorem sed quasi quo obcaecati maiores, eos minus dolorum ullam quidem, voluptatibus, odio praesentium a! Inventore ad nesciunt error molestias consequuntur qui nemo vitae, distinctio necessitatibus cumque debitis laudantium dignissimos ex accusantium explicabo neque quasi? Dolore, libero porro earum a ipsa nobis quod consequuntur aut maxime repellat expedita cum quaerat labore recusandae voluptas iusto esse ad, sit commodi debitis, excepturi velit nulla accusantium. A eveniet excepturi nihil eaque eligendi repudiandae, eos suscipit rerum iure veritatis modi incidunt, quos hic mollitia impedit. Repellat placeat ut velit, id molestiae eos tenetur aspernatur. Vero, enim repellat. Illo unde, perferendis ducimus dolor mollitia minima perspiciatis, voluptatum explicabo quam, sit fugiat. Reiciendis veritatis cupiditate laudantium cum voluptate eveniet nihil cumque provident, odit possimus, optio culpa facere eos perferendis!
        </p>
        <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit reprehenderit soluta explicabo, quam ea, alias maxime praesentium pariatur quia, distinctio sed quasi corporis eum perferendis. Fugiat dolorem ratione ipsa commodi. Dicta harum velit quam sint tempore eveniet minima? Asperiores, harum. Tempore deserunt quaerat cumque? Fugiat, est autem unde libero incidunt magni expedita vero nostrum accusantium, soluta, impedit illo assumenda cupiditate quo totam. Eaque amet ipsa laboriosam itaque, incidunt totam inventore nemo reprehenderit porro quos tenetur animi enim! Dolorem sed quasi quo obcaecati maiores, eos minus dolorum ullam quidem, voluptatibus, odio praesentium a! Inventore ad nesciunt error molestias consequuntur qui nemo vitae, distinctio necessitatibus cumque debitis laudantium dignissimos ex accusantium explicabo neque quasi? Dolore, libero porro earum a ipsa nobis quod consequuntur aut maxime repellat expedita cum quaerat labore recusandae voluptas iusto esse ad, sit commodi debitis, excepturi velit nulla accusantium. A eveniet excepturi nihil eaque eligendi repudiandae, eos suscipit rerum iure veritatis modi incidunt, quos hic mollitia impedit. Repellat placeat ut velit, id molestiae eos tenetur aspernatur. Vero, enim repellat. Illo unde, perferendis ducimus dolor mollitia minima perspiciatis, voluptatum explicabo quam, sit fugiat. Reiciendis veritatis cupiditate laudantium cum voluptate eveniet nihil cumque provident, odit possimus, optio culpa facere eos perferendis!
        </p>
    </main>
  )
}

export default App